blank_issues_enabled: false
contact_links:
  - name: Template Examples
    url: https://github.com/rafsodc/sodc-web/blob/main/.github/ISSUE_TEMPLATE_EXAMPLES.md
    about: See examples for filling out issue templates